#CPU makefile
all: 
	-$(CC) -o ../../bin/cpu cpu.c -lcommons -lparser-ansisop -lComunicacion -L"../../bin"

debug: 
	-$(CC) -g -o ../../debug/cpu cpu.c -lcommons -lparser-ansisop -lComunicacion -L"../../bin"
	

