#CPU makefile
all: 
	-$(CC) -o ../../bin/file_system file_system.c -lcommons -lComunicacion -L"../../bin"

debug: 
	-$(CC) -g -o  ../../debug/file_system file_system.c -lcommons -lComunicacion -L"../../bin"
	

