#Consola makefile
SRCS = $(wildcard *.c)

all: 
	-$(CC) -o ../../bin/consola $(SRCS) -lcommons -lpthread -lComunicacion -L"../../bin"

debug: 
	-$(CC) -g -o ../../debug/consola $(SRCS) -lcommons -lpthread -lComunicacion -L"../../bin"

	

